#!/bin/sh
set -e

PWD=$(pwd)

DIR=$(pwd)
while [ "${DIR}" != "/" -a ! -e "${DIR}/Vagrantfile" ]; do
  cd ..
  DIR=$(pwd)
done
SSH_CONFIG="${DIR}/.ssh_config"

cd "${PWD}"

if [ "$1" == "-t" ]; then
  TTY="$1"
  shift
fi

HOST=$1

trap "rm -f '${SSH_CONFIG}'" ERR
if [ ! -e "${SSH_CONFIG}" ]; then
  vagrant ssh-config > "${SSH_CONFIG}"
fi
if test -z "${HOST}" || ! grep -q "^Host ${HOST}$" "${SSH_CONFIG}" 2>/dev/null; then
  HOST=$(awk '/^Host/{print $2}' "${SSH_CONFIG}" 2>/dev/null | head -n 1)
else
  shift
fi
ssh -F "${SSH_CONFIG}" "${HOST}" exit
trap "" ERR

if [ $# -ne 0 ]; then
  cmd=("${@//\"/\\\"}")
  cmd=("${cmd[@]/#/\"}")
  cmd="${cmd[@]/%/\"}"
  ssh ${TTY} -F "${SSH_CONFIG}" "${HOST}" bash -l -c "'${cmd}'"
else
  ssh -F "${SSH_CONFIG}" "${HOST}"
fi
